service: lambda-locally-with-serverless-framework

frameworkVersion: '2'

plugins:
  - serverless-plugin-typescript
  - serverless-offline

provider:
  name: aws
  region: us-east-1
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221
  stage: ${opt:stage, "local"}

functions:
  # create:
  #   handler: src/handler.create
  #   events:
  #     - http:
  #         path: products
  #         method: post

  # update:
  #   handler: src/handler.update
  #   events:
  #     - http:
  #         path: products/{id}
  #         method: put

  # find:
  #   handler: src/handler.find
  #   events:
  #     - http:
  #         path: products
  #         method: get

  # findOne:
  #   handler: src/handler.findOne
  #   events:
  #     - http:
  #         path: products/{id}
  #         method: get

  # deleteOne:
  #   handler: src/handler.deleteOne
  #   events:
  #     - http:
  #         path: products/{id}
  #         method: delete

  updatePicture:
    handler: src/handler.updatePicture
    events:
      - http:
          path: products/{id}/picture
          method: patch
